### PR TITLE
Added datagram socket support

### PR DESCRIPTION
**Pull request by hannesg**
Hi

I'd like to run a custom dns server with crank. I think supporting datagram sockets would be useful feature.

Cheers'
Hannes

### CODE REVIEW

**Comment by zimbatm** [comment]
Thanks @hannesg

**Comment by zimbatm** [comment]
I think it's valid, you might also want to take a look at opening the port with SO_REUSEADDR and not binding with crank.

**Comment by hannesg** [comment]
Thanks!

Yeah would be an option. For servers like dns that work with udp and tcp I'm currently trying to just pass them whatever socket type I want and let the service not care about such details.

**Comment by zimbatm** [comment]
Yeah both work, it's good to have options :) Let me know when you have it deployed, it would be interesting to make an article on that.

**Pull request merged**
